### ISSUE TITLE
Repo Installation Issue

### ISSUE THREAD

**Issue by wonggwan** [CraftJarvis/MC-Planner#2] opened 2023-03-22 21:46 UTC
Hi,

Thanks for the great work!

When I was installing following your command, I managed to go through all the steps (create conda, install the requirements.txt, etc...) and no error message was shown, but after I downloaded the model checkpoint and put my OpenAI key to the txt file and run the command, it shows that:

```python
from minedojo.minedojo_wrapper import MineDojoEnv
ModuleNotFoundError: No module named 'minedojo.minedojo_wrapper'
```

Yet when I go to validate my installation of minedojo, it did pops up the MC page and the agent played the game for a short time and says validation was completed.

[UPDATE]: 

Another error:

```python 
from ray.rllib.models.torch.vpt_backbone import VPTBackbone
ModuleNotFoundError: No module named 'ray.rllib.models.torch.vpt_backbone'
```

Could you please tell me how to fix this?

Thanks!

**Comment by zhwang4ai** [comment] 2023-03-25 03:32
1. We wrap the original Minedojo to support our controller.
Please `python -m pip install git+https://github.com/CraftJarvis/MC-Simulator.git` to install our modified simulator.
2. the error has been fixed in the updated code.

**Comment by wonggwan** [comment] 2023-03-27 21:21
[UPDATE]

Thank you for your reply! I tried to download the new repo and install your controller as well, yet it shows something new:

```python
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Traceback (most recent call last):
  File "/home/wonggwan/Downloads/MC-Planner/main.py", line 5, in <module>
    from controller import *
  File "/home/wonggwan/Downloads/MC-Planner/controller.py", line 270, in <module>
    from ray.rllib.models.torch.mineclip_lib.mineclip_model import MineCLIP
ModuleNotFoundError: No module named 'ray.rllib.models.torch.mineclip_lib'
```

**Comment by zhwang4ai** [comment] 2023-03-28 13:19
We apologize for the inconvenience caused by the inclusion of Ray in our early code, which was not properly cleaned up in this version. We have reviewed the code and removed any redundant code related to Ray.
Moreover, due to the cancellation of access to Codex by OpenAI, DEPS based on Codex are no longer supported. You can choose to use the Davinci-model or wait for our update to ChatGPT, which has better performance. We will release DEPS based on ChatGPT as soon as possible.

**Closed** 2023-03-29 09:36 UTC
